apiVersion: v1
kind: Service
metadata:
  name: Automated-Demo
  namespace: automate-namespace
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: Automated-Demo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000